### ISSUE TITLE
[1.18.2] Golden Hopper has no breaking tool

### ISSUE THREAD

**Issue by ffuentesm** [MrCrayfish/GoldenHopper#21] opened 2022-04-22 20:05 UTC
ver: goldenhopper-1.2.6-1.18.2.jar

The Golden Hopper has no breaking tool and does not drop when broken

![image](https://user-images.githubusercontent.com/44974827/164786111-23815129-7d71-46e2-bc47-a533cdfedf66.png)

**Comment by MrCrayfish** [comment] 2024-09-30 03:38
Sorry for the delay and thanks for the original support. Due to the time elapsed since this report, I no longer maintain 1.18.2 versions of my mods. The issue is however resolved in modern versions.

**Closed as completed by MrCrayfish** 2024-09-30 03:38 UTC
